spring.application.name=ecommerce-backend

# ----------------------------------Database Configuration----------------------------------------

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true

server.port=${PORT:10000}
server.address=0.0.0.0

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# WhatsApp Cloud API
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.api-url=https://graph.facebook.com/v25.0
whatsapp.template-name=confirmed_orders
whatsapp.template-language=en
whatsapp.confirmed-order-image-url=https://my-e-commerce-backend-s3.s3.eu-north-1.amazonaws.com/whatsapp/order-confirmed.png

# Gemini
gemini.model=gemini-3.7-flash
gemini.api-key=${GEMINI_API_KEY}

#aws
aws.s3.bucket-name=my-e-commerce-backend-s3
aws.region=eu-north-1
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}