spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:mysql://cloud.layerbase.dev:41053/e_commerce?useSSL=true&requireSSL=true
spring.datasource.username=root
spring.datasource.password=YOUR_LAYERBASE_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true

server.port=${PORT:10000}
server.address=0.0.0.0

jwt.secret=MyVerySecretKeyForEcommerceProjectThatIsLongEnough123456
jwt.expiration=86400000

# WhatsApp Cloud API
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.api-url=https://graph.facebook.com/v25.0
whatsapp.template-name=order_confirmation
whatsapp.template-language=en

# Gemini
gemini.model=gemini-3.7-flash